@baseUrl = http://localhost:3000

GET {{baseUrl}}

### 

GET {{baseUrl}}/users

### 

GET {{baseUrl}}/users/25c2d981-71aa-4239-bde1-9b81ac139460

###

POST {{baseUrl}}/users
Content-Type: application/json

{ 
	"name": "Smith",
	"username": "smith" 
}
